import Head from 'next/head'
import { useEffect, useState } from 'react';
import Navbar from '../components/Navbar';
import TaskForm from '../components/TaskForm';
import TaskList from '../components/TaskList'
import { supabaseClient } from '../lib/client';

const task1 = {
  name: "Sample Task",
  description: "Sample Description",
  status: 1,
  created_at: "Monday",
};

export default function Home() {
  const [todos, setTodos] = useState([]);
  useEffect(() => {
    fetchTodos();
  }, [])
  async function fetchTodos() {
    const { data } = await supabaseClient.from('tasks').select();
    console.log(data);
    setTodos(data);
  }
  async function changeStatus(status, id) {
    console.log(status, id);
    const { error } = await supabaseClient.from('tasks').update({ status: status ? 1 : 0 }).eq('id', id);
    console.log(error);
  }
  async function createTodo(task, desc, status) {
    if (task === "" || task === null)
      return;
    const { error } = await supabaseClient
      .from('tasks')
      .insert({ name: task, description: desc, status: status ? 1 : 0 })
  }
  async function deleteTodo(id) {
    const { error } = await supabaseClient
      .from('tasks')
      .delete()
      .eq('id', id)
  }
  async function deleteCompletedTodos() {
    const { error } = await supabaseClient
      .from('tasks')
      .delete()
      .eq('status', 1)
  }
  return (
    <div>
      <Head>
        <title>My To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar deleteAll={deleteCompletedTodos} />
      <TaskList tasks={todos} onChange={changeStatus} onDelete={deleteTodo} />
      <TaskForm onClick={createTodo} />
    </div>
  )
}
