import Head from 'next/head'
import { useEffect, useState } from 'react';
import ConfirmMoadal from '../components/ConfirmModal';
import Navbar from '../components/Navbar';
import TaskForm from '../components/TaskForm';
import TaskList from '../components/TaskList'
import { supabaseClient } from '../lib/client';


export default function Home() {
  const [todos, setTodos] = useState([]);
  useEffect(() => {
    fetchTodos();
  }, [])
  async function fetchTodos() {
    const { data } = await supabaseClient.from('tasks').select();
    setTodos(data);
  }
  async function changeStatus(status, id) {
    const { error } = await supabaseClient.from('tasks').update({ status: status ? 1 : 0 }).eq('id', id);
  }
  async function createTodo(task, desc, status) {
    if (task === "" || task === null)
      return;
    const { error } = await supabaseClient
      .from('tasks')
      .insert({ name: task, description: desc, status: status ? 1 : 0 });
    fetchTodos();
  }
  async function deleteTodo(id) {
    const { error } = await supabaseClient
      .from('tasks')
      .delete()
      .eq('id', id);
    fetchTodos();
  }
  async function deleteCompletedTodos() {
    const { error } = await supabaseClient
      .from('tasks')
      .delete()
      .eq('status', 1);
    fetchTodos();
  }
  return (
    <div>
      <Head>
        <title>My To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar deleteAll={deleteCompletedTodos} />
      <TaskList tasks={todos} onChange={changeStatus} onDelete={deleteTodo} />
      <TaskForm onClick={createTodo} />
      <ConfirmMoadal onClick={deleteCompletedTodos} />
    </div>
  )
}
